[package]
name = "worm"
version = "0.1.0"
edition = "2021"
default-run = "worm"

[dependencies]
x11rb = { version = "*", features = ["xinerama"] }
dirs = "*"
clap = "3.0.0-beta.4"
anyhow = "1.0.44"

[profile.release]
lto = true
opt-level = 'z'

[[bin]]
name = "wormc"
path = "src/wormc.rs"
